# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('max_users', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartyName', models.CharField(max_length=100)),
                ('PartyPhoneNumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PTA.Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_millions', models.DecimalField(decimal_places=2, max_digits=100)),
                ('CurrencyPair', models.CharField(choices=[('GBPUSD', 'GBPUSD'), ('USDCHF', 'USDCHF'), ('USDEUR', 'USDEUR'), ('USDCNY', 'USDJPY'), ('USDCAD', 'USDCAD')], max_length=6)),
                ('Rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ModifiedByID', models.BigIntegerField(max_length=50)),
                ('TradeType', models.CharField(choices=[('SPOT', 'SPOT'), ('OTHER', 'OTHER')], max_length=6)),
                ('TimePushed', models.BigIntegerField(blank=True, default=None, null=True)),
                ('TimeActioned', models.BigIntegerField(blank=True, default=None, null=True)),
                ('Status', models.CharField(choices=[('PENDING', 'PENDING'), ('AFFIRMED', 'AFFIRMED'), ('REJECTED', 'REJECTED')], max_length=50)),
                ('Reason', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('BuyerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to='PTA.Party')),
                ('Institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTA.Institution')),
                ('SellerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PTA.Party')),
            ],
        ),
    ]
